ALTER TABLE tenants ADD COLUMN IF NOT EXISTS qris_enabled BOOLEAN DEFAULT false;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS report_enabled BOOLEAN DEFAULT false;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS report_time VARCHAR(10) DEFAULT '07:00';
