ALTER TABLE users ADD COLUMN parent_id UUID REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE tasks ADD COLUMN created_by UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN assigned_to UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN verification_type VARCHAR(50) DEFAULT 'auto';
ALTER TABLE tasks ADD COLUMN proof_image VARCHAR(255);
ALTER TABLE tasks ADD COLUMN gps_location VARCHAR(255);
ALTER TABLE tasks ADD COLUMN is_verified BOOLEAN DEFAULT false;

ALTER TABLE voters ADD COLUMN potential_level VARCHAR(50);
ALTER TABLE voters ADD COLUMN competitor_support VARCHAR(255);
