package main

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

const (
	layoutDateISO        = "2006-01-02"
	layoutDateDisplay   = "2 January 2006"
	layoutDateTimeFull  = "2 January 2006 15:04 MST"
	errPDFGenFailed     = "PDF generation failed"
	errMissingParamsInc = "Missing X-Tenant-ID, from, or to"
	errMissingParamsBal = "Missing X-Tenant-ID or date"
	tidakAda             = "(tidak ada)"
)

func pdfHeader(businessName, title, period string) *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(0, 8, businessName)
	pdf.Ln(8)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 7, title)
	pdf.Ln(7)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(0, 5, period)
	pdf.Ln(5)
	pdf.Cell(0, 5, "Dicetak: "+time.Now().Format(layoutDateTimeFull))
	pdf.Ln(8)
	return pdf
}

func pdfRespond(w http.ResponseWriter, pdf *gofpdf.Fpdf, filename string) {
	pdf.SetFont("Arial", "I", 8)
	pdf.SetY(-20)
	pdf.Cell(0, 4, "Generated by WCH Platform")
	pdf.Ln(4)
	pdf.Cell(0, 4, fmt.Sprintf("Halaman %d dari {nb}", pdf.PageNo()))
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		writeJSON(w, http.StatusInternalServerError, APIResponse{Message: "PDF generation failed: " + err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.pdf\"", filename))
	w.Header().Set("Content-Length", strconv.Itoa(buf.Len()))
	w.Write(buf.Bytes())
}

func formatIDR(rupiah int64) string {
	negative := ""
	abs := rupiah
	if abs < 0 {
		negative = "("
		rupiah = -rupiah
		abs = rupiah
	}
	s := strconv.FormatInt(abs, 10)
	n := len(s)
	if n <= 3 {
		return negative + "Rp " + s + ")"
	}
	var b strings.Builder
	b.WriteString("Rp ")
	pre := n % 3
	if pre > 0 {
		b.WriteString(s[:pre])
		if n > pre {
			b.WriteString(".")
		}
	}
	for i := pre; i < n; i += 3 {
		b.WriteString(s[i : i+3])
		if i+3 < n {
			b.WriteString(".")
		}
	}
	if negative != "" {
		b.WriteString(")")
	}
	return b.String()
}

func handleIncomeStatementPDF(w http.ResponseWriter, r *http.Request) {
	tenantID := r.Header.Get("X-Tenant-ID")
	from := r.URL.Query().Get("from")
	to := r.URL.Query().Get("to")
	if tenantID == "" || from == "" || to == "" {
		writeJSON(w, http.StatusBadRequest, APIResponse{Message: errMissingParamsInc})
		return
	}
	businessName := getTenantBusinessName(r.Context(), tenantID)
	revRows, expRows, revenue, expense := queryIncomeData(r.Context(), tenantID, from, to)
	netIncome := revenue - expense
	renderIncomeStatementPDF(w, businessName, from, to, revRows, expRows, revenue, expense, netIncome)
}

func getTenantBusinessName(ctx context.Context, tenantID string) string {
	var name *string
	DB.QueryRow(ctx, `SELECT COALESCE(business_name, name) FROM tenants WHERE id = $1`, tenantID).Scan(&name)
	if name != nil {
		return *name
	}
	return "UMKM WCH"
}

type incomeRow struct{ Typ, Name string; Balance int64 }

func queryIncomeData(ctx context.Context, tenantID, from, to string) ([]incomeRow, []incomeRow, int64, int64) {
	var revenue, expense int64
	var revRows, expRows []incomeRow
	rows, err := DB.Query(ctx, `
		SELECT c.type, c.name, SUM(l.credit - l.debit) as balance
		FROM journal_lines l
		JOIN journal_entries e ON l.entry_id = e.id
		JOIN chart_of_accounts c ON l.account_id = c.id
		WHERE e.tenant_id = $1 AND c.type IN ('revenue', 'expense') AND e.date >= $2 AND e.date <= $3
		GROUP BY c.type, c.name
	`, tenantID, from, to)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var t, n string
			var b int64
			if err := rows.Scan(&t, &n, &b); err == nil {
				if t == "expense" {
					b = -b
					expense += b
					expRows = append(expRows, incomeRow{Typ: t, Name: n, Balance: b})
				} else {
					revenue += b
					revRows = append(revRows, incomeRow{Typ: t, Name: n, Balance: b})
				}
			}
		}
	}
	return revRows, expRows, revenue, expense
}

func renderIncomeStatementPDF(w http.ResponseWriter, businessName, from, to string, revRows, expRows []incomeRow, revenue, expense, netIncome int64) {
	fromDate, _ := time.Parse(layoutDateISO, from)
	toDate, _ := time.Parse(layoutDateISO, to)
	pdf := pdfHeader(businessName, "Laporan Laba Rugi",
		fmt.Sprintf("Periode: %s – %s", fromDate.Format(layoutDateDisplay), toDate.Format(layoutDateDisplay)))
	pdfLineItem := func(label string, amount int64) {
		pdf.Cell(110, 5, "  "+label)
		pdf.CellFormat(60, 5, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(5)
	}
	pdfSection := func(title string) {
		pdf.SetFont("Arial", "B", 11)
		pdf.Cell(0, 7, title)
		pdf.Ln(7)
		pdf.SetFont("Arial", "", 10)
	}
	pdfTotal := func(label string, amount int64) {
		pdf.SetFont("Arial", "B", 10)
		pdf.Cell(110, 6, label)
		pdf.CellFormat(60, 6, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(6)
		pdf.SetFont("Arial", "", 10)
	}
	pdfSection("PENDAPATAN")
	for _, r := range revRows {
		pdfLineItem(r.Name, r.Balance)
	}
	if len(revRows) == 0 {
		pdfLineItem(tidakAda, 0)
	}
	pdfTotal("Total Pendapatan", revenue)
	pdf.Ln(3)
	pdfSection("BEBAN")
	for _, r := range expRows {
		pdfLineItem(r.Name, -r.Balance)
	}
	if len(expRows) == 0 {
		pdfLineItem(tidakAda, 0)
	}
	pdfTotal("Total Beban", -expense)
	pdf.Ln(3)
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(110, 8, "LABA / (RUGI) BERSIH")
	pdf.CellFormat(60, 8, formatIDR(netIncome), "", 0, "R", false, 0, "")
	pdfRespond(w, pdf, fmt.Sprintf("laba-rugi_%s_%s", from, to))
}

func handleBalanceSheetPDF(w http.ResponseWriter, r *http.Request) {
	tenantID := r.Header.Get("X-Tenant-ID")
	date := r.URL.Query().Get("date")
	if tenantID == "" || date == "" {
		writeJSON(w, http.StatusBadRequest, APIResponse{Message: errMissingParamsBal})
		return
	}
	businessName := getTenantBusinessName(r.Context(), tenantID)
	assetRows, liabRows, eqRows, assets, liab, equity := queryBalanceData(r.Context(), tenantID, date)
	renderBalanceSheetPDF(w, businessName, date, assetRows, liabRows, eqRows, assets, liab, equity)
}

type balanceRow struct{ Typ, Name string; Balance int64 }

func queryBalanceData(ctx context.Context, tenantID, date string) ([]balanceRow, []balanceRow, []balanceRow, int64, int64, int64) {
	var assets, liab, equity int64
	var assetRows, liabRows, eqRows []balanceRow
	rows, err := DB.Query(ctx, `
		SELECT c.type, c.name, SUM(l.debit - l.credit) as balance
		FROM journal_lines l
		JOIN journal_entries e ON l.entry_id = e.id
		JOIN chart_of_accounts c ON l.account_id = c.id
		WHERE e.tenant_id = $1 AND e.date <= $2
		GROUP BY c.type, c.name
	`, tenantID, date)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var t, n string
			var b int64
			if err := rows.Scan(&t, &n, &b); err == nil {
				switch t {
				case "liability":
					liabRows = append(liabRows, balanceRow{Typ: t, Name: n, Balance: b})
					liab += b
				case "equity":
					eqRows = append(eqRows, balanceRow{Typ: t, Name: n, Balance: b})
					equity += b
				default:
					assetRows = append(assetRows, balanceRow{Typ: t, Name: n, Balance: b})
					assets += b
				}
			}
		}
	}
	return assetRows, liabRows, eqRows, assets, liab, equity
}

func renderBalanceSheetPDF(w http.ResponseWriter, businessName, date string, assetRows, liabRows, eqRows []balanceRow, assets, liab, equity int64) {
	dateParsed, _ := time.Parse(layoutDateISO, date)
	pdf := pdfHeader(businessName, "Neraca (Balance Sheet)",
		fmt.Sprintf("Per tanggal: %s", dateParsed.Format(layoutDateDisplay)))
	pdfLine := func(label string, amount int64) {
		pdf.Cell(110, 5, "  "+label)
		pdf.CellFormat(60, 5, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(5)
	}
	pdfSection := func(title string) {
		pdf.SetFont("Arial", "B", 11)
		pdf.Cell(0, 7, title)
		pdf.Ln(7)
		pdf.SetFont("Arial", "", 10)
	}
	pdfTotal := func(label string, amount int64) {
		pdf.SetFont("Arial", "B", 10)
		pdf.Cell(110, 6, label)
		pdf.CellFormat(60, 6, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(6)
		pdf.SetFont("Arial", "", 10)
	}
	pdfSection("ASET")
	for _, r := range assetRows {
		pdfLine(r.Name, r.Balance)
	}
	if len(assetRows) == 0 {
		pdfLine(tidakAda, 0)
	}
	pdfTotal("Total Aset", assets)
	pdf.Ln(3)
	pdfSection("LIABILITAS")
	for _, r := range liabRows {
		pdfLine(r.Name, -r.Balance)
	}
	if len(liabRows) == 0 {
		pdfLine(tidakAda, 0)
	}
	pdfTotal("Total Liabilitas", -liab)
	pdf.Ln(3)
	pdfSection("EKUITAS")
	for _, r := range eqRows {
		pdfLine(r.Name, -r.Balance)
	}
	if len(eqRows) == 0 {
		pdfLine(tidakAda, 0)
	}
	pdfTotal("Total Ekuitas", -equity)
	pdf.Ln(5)
	pdfSummaryBalanceSheet(pdf, assets, liab, equity)
	pdfRespond(w, pdf, fmt.Sprintf("neraca_%s", date))
}

func pdfSummaryBalanceSheet(pdf *gofpdf.Fpdf, assets, liab, equity int64) {
	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(0, 7, "RINGKASAN")
	pdf.Ln(7)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(110, 6, "Total Aset")
	pdf.CellFormat(60, 6, formatIDR(assets), "", 0, "R", false, 0, "")
	pdf.Ln(6)
	pdf.Cell(110, 6, "Total Liabilitas + Ekuitas")
	pdf.CellFormat(60, 6, formatIDR(liab+equity), "", 0, "R", false, 0, "")
	pdf.Ln(6)
	if assets != (liab + equity) {
		pdf.SetTextColor(220, 38, 38)
		pdf.Cell(0, 6, fmt.Sprintf("Neraca tidak balance — selisih %s", formatIDR(assets-(liab+equity))))
	} else {
		pdf.SetTextColor(16, 185, 129)
		pdf.Cell(0, 6, "Neraca balance")
	}
	pdf.SetTextColor(0, 0, 0)
}
