package main

import (
	"bytes"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

func pdfHeader(businessName, title, period string) *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(0, 8, businessName)
	pdf.Ln(8)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 7, title)
	pdf.Ln(7)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(0, 5, period)
	pdf.Ln(5)
	pdf.Cell(0, 5, "Dicetak: "+time.Now().Format("2 January 2006 15:04 MST"))
	pdf.Ln(8)
	return pdf
}

func pdfRespond(w http.ResponseWriter, pdf *gofpdf.Fpdf, filename string) {
	pdf.SetFont("Arial", "I", 8)
	pdf.SetY(-20)
	pdf.Cell(0, 4, "Generated by WCH Platform")
	pdf.Ln(4)
	pdf.Cell(0, 4, fmt.Sprintf("Halaman %d dari {nb}", pdf.PageNo()))
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		writeJSON(w, http.StatusInternalServerError, APIResponse{Message: "PDF generation failed: " + err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.pdf\"", filename))
	w.Header().Set("Content-Length", strconv.Itoa(buf.Len()))
	w.Write(buf.Bytes())
}

func formatIDR(rupiah int64) string {
	negative := ""
	abs := rupiah
	if abs < 0 {
		negative = "("
		rupiah = -rupiah
		abs = rupiah
	}
	s := strconv.FormatInt(abs, 10)
	n := len(s)
	if n <= 3 {
		return negative + "Rp " + s + ")"
	}
	var b strings.Builder
	b.WriteString("Rp ")
	pre := n % 3
	if pre > 0 {
		b.WriteString(s[:pre])
		if n > pre {
			b.WriteString(".")
		}
	}
	for i := pre; i < n; i += 3 {
		b.WriteString(s[i : i+3])
		if i+3 < n {
			b.WriteString(".")
		}
	}
	if negative != "" {
		b.WriteString(")")
	}
	return b.String()
}

func handleIncomeStatementPDF(w http.ResponseWriter, r *http.Request) {
	tenantID := r.Header.Get("X-Tenant-ID")
	from := r.URL.Query().Get("from")
	to := r.URL.Query().Get("to")
	if tenantID == "" || from == "" || to == "" {
		writeJSON(w, http.StatusBadRequest, APIResponse{Message: "Missing X-Tenant-ID, from, or to"})
		return
	}
	businessName := "UMKM WCH"
	var bn *string
	DB.QueryRow(r.Context(), `SELECT COALESCE(business_name, name) FROM tenants WHERE id = $1`, tenantID).Scan(&bn)
	if bn != nil {
		businessName = *bn
	}

	type row struct {
		Typ     string
		Name    string
		Balance int64
	}
	var revenue, expense int64
	var revRows, expRows []row
	rows, err := DB.Query(r.Context(), `
		SELECT c.type, c.name, SUM(l.credit - l.debit) as balance
		FROM journal_lines l
		JOIN journal_entries e ON l.entry_id = e.id
		JOIN chart_of_accounts c ON l.account_id = c.id
		WHERE e.tenant_id = $1 AND c.type IN ('revenue', 'expense') AND e.date >= $2 AND e.date <= $3
		GROUP BY c.type, c.name
	`, tenantID, from, to)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var t, n string
			var b int64
			if err := rows.Scan(&t, &n, &b); err == nil {
				if t == "expense" {
					b = -b
					expense += b
					expRows = append(expRows, row{Typ: t, Name: n, Balance: b})
				} else {
					revenue += b
					revRows = append(revRows, row{Typ: t, Name: n, Balance: b})
				}
			}
		}
	}
	netIncome := revenue - expense
	fromDate, _ := time.Parse("2006-01-02", from)
	toDate, _ := time.Parse("2006-01-02", to)
	pdf := pdfHeader(businessName, "Laporan Laba Rugi",
		fmt.Sprintf("Periode: %s – %s", fromDate.Format("2 January 2006"), toDate.Format("2 January 2006")))

	section := func(title string) {
		pdf.SetFont("Arial", "B", 11)
		pdf.Cell(0, 7, title)
		pdf.Ln(7)
		pdf.SetFont("Arial", "", 10)
	}
	totalLine := func(label string, amount int64) {
		pdf.SetFont("Arial", "B", 10)
		pdf.Cell(110, 6, label)
		pdf.CellFormat(60, 6, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(6)
		pdf.SetFont("Arial", "", 10)
	}
	itemLine := func(label string, amount int64) {
		pdf.Cell(110, 5, "  "+label)
		pdf.CellFormat(60, 5, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(5)
	}

	section("PENDAPATAN")
	for _, r := range revRows {
		itemLine(r.Name, r.Balance)
	}
	if len(revRows) == 0 {
		itemLine("(tidak ada)", 0)
	}
	totalLine("Total Pendapatan", revenue)
	pdf.Ln(3)
	section("BEBAN")
	for _, r := range expRows {
		itemLine(r.Name, -r.Balance)
	}
	if len(expRows) == 0 {
		itemLine("(tidak ada)", 0)
	}
	totalLine("Total Beban", -expense)
	pdf.Ln(3)
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(110, 8, "LABA / (RUGI) BERSIH")
	pdf.CellFormat(60, 8, formatIDR(netIncome), "", 0, "R", false, 0, "")
	pdfRespond(w, pdf, fmt.Sprintf("laba-rugi_%s_%s", from, to))
}

func handleBalanceSheetPDF(w http.ResponseWriter, r *http.Request) {
	tenantID := r.Header.Get("X-Tenant-ID")
	date := r.URL.Query().Get("date")
	if tenantID == "" || date == "" {
		writeJSON(w, http.StatusBadRequest, APIResponse{Message: "Missing X-Tenant-ID or date"})
		return
	}
	businessName := "UMKM WCH"
	var bn *string
	DB.QueryRow(r.Context(), `SELECT COALESCE(business_name, name) FROM tenants WHERE id = $1`, tenantID).Scan(&bn)
	if bn != nil {
		businessName = *bn
	}

	type row struct {
		Typ     string
		Name    string
		Balance int64
	}
	var assets, liab, equity int64
	var assetRows, liabRows, eqRows []row
	rows, err := DB.Query(r.Context(), `
		SELECT c.type, c.name, SUM(l.debit - l.credit) as balance
		FROM journal_lines l
		JOIN journal_entries e ON l.entry_id = e.id
		JOIN chart_of_accounts c ON l.account_id = c.id
		WHERE e.tenant_id = $1 AND e.date <= $2
		GROUP BY c.type, c.name
	`, tenantID, date)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var t, n string
			var b int64
			if err := rows.Scan(&t, &n, &b); err == nil {
				switch t {
				case "liability":
					b = -b
					liab += b
					liabRows = append(liabRows, row{Typ: t, Name: n, Balance: b})
				case "equity":
					b = -b
					equity += b
					eqRows = append(eqRows, row{Typ: t, Name: n, Balance: b})
				default:
					assets += b
					assetRows = append(assetRows, row{Typ: t, Name: n, Balance: b})
				}
			}
		}
	}
	dateParsed, _ := time.Parse("2006-01-02", date)
	pdf := pdfHeader(businessName, "Neraca (Balance Sheet)",
		fmt.Sprintf("Per tanggal: %s", dateParsed.Format("2 January 2006")))

	section := func(title string) {
		pdf.SetFont("Arial", "B", 11)
		pdf.Cell(0, 7, title)
		pdf.Ln(7)
		pdf.SetFont("Arial", "", 10)
	}
	totalLine := func(label string, amount int64) {
		pdf.SetFont("Arial", "B", 10)
		pdf.Cell(110, 6, label)
		pdf.CellFormat(60, 6, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(6)
		pdf.SetFont("Arial", "", 10)
	}
	itemLine := func(label string, amount int64) {
		pdf.Cell(110, 5, "  "+label)
		pdf.CellFormat(60, 5, formatIDR(amount), "", 0, "R", false, 0, "")
		pdf.Ln(5)
	}

	section("ASET")
	for _, r := range assetRows {
		itemLine(r.Name, r.Balance)
	}
	if len(assetRows) == 0 {
		itemLine("(tidak ada)", 0)
	}
	totalLine("Total Aset", assets)
	pdf.Ln(3)
	section("LIABILITAS")
	for _, r := range liabRows {
		itemLine(r.Name, -r.Balance)
	}
	if len(liabRows) == 0 {
		itemLine("(tidak ada)", 0)
	}
	totalLine("Total Liabilitas", -liab)
	pdf.Ln(3)
	section("EKUITAS")
	for _, r := range eqRows {
		itemLine(r.Name, -r.Balance)
	}
	if len(eqRows) == 0 {
		itemLine("(tidak ada)", 0)
	}
	totalLine("Total Ekuitas", -equity)
	pdf.Ln(5)

	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(0, 7, "RINGKASAN")
	pdf.Ln(7)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(110, 6, "Total Aset")
	pdf.CellFormat(60, 6, formatIDR(assets), "", 0, "R", false, 0, "")
	pdf.Ln(6)
	pdf.Cell(110, 6, "Total Liabilitas + Ekuitas")
	pdf.CellFormat(60, 6, formatIDR(liab+equity), "", 0, "R", false, 0, "")
	pdf.Ln(6)
	if assets != (liab + equity) {
		pdf.SetTextColor(220, 38, 38)
		pdf.Cell(0, 6, fmt.Sprintf("Neraca tidak balance — selisih %s", formatIDR(assets-(liab+equity))))
		pdf.SetTextColor(0, 0, 0)
	} else {
		pdf.SetTextColor(16, 185, 129)
		pdf.Cell(0, 6, "Neraca balance")
		pdf.SetTextColor(0, 0, 0)
	}

	pdfRespond(w, pdf, fmt.Sprintf("neraca_%s", date))
}
